### ISSUE TITLE
Actividad 2. Infografia

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-2-infografia-AdriHernandez-Martinez0863#2]
Actividad 2. Infografia
Adriana Hernandez Martinez 1BS
Infografía Construcción del conocimiento.pdf…]()

**Comment by AdriHernandez-Martinez0863** [comment]
Actividad 2. Infografia
Adriana Hernandez Martinez 1BS
[Infografía Construcción del conocimiento.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-AdriHernandez-Martinez0863/files/9450026/Infografia.Construccion.del.conocimiento.pdf)

**Comment by Jaczibeth** [comment]
de 20% sacaste  18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
